enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npm.taobao.org"

httpProxy: "http://127.0.0.1:8118"

httpsProxy: "https://127.0.0.1:8118"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
